#!/usr/bin/env python3
"""Validate curated metadata and deterministically render the index and call graph."""
from __future__ import annotations
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
KINDS = {'function', 'code_label', 'flash_data', 'ram_object', 'ram_data'}
RELATIONS = {'direct_call', 'indirect_call', 'function_pointer', 'contains',
             'data_reference', 'data_access', 'data_write', 'conditional_path', 'shared_buffer'}
STATUS = {'confirmed_static', 'supported', 'hypothesis'}


def address(value: object) -> int:
    if not isinstance(value, str) or not re.fullmatch(r'0x[0-9a-f]{8}', value):
        raise ValueError(f'Expected normalized address, got {value!r}')
    return int(value, 16)


def validate(data: dict) -> None:
    if data.get('schema_version') != 1:
        raise ValueError('Unsupported map schema')
    image = data['image']
    first = address(image['base'])
    length = image['length']
    if not isinstance(length, int) or length <= 0:
        raise ValueError('Invalid image length')
    if not re.fullmatch(r'[0-9a-f]{64}', image['sha256']):
        raise ValueError('Invalid image digest')
    ids = set()
    for node in data['nodes']:
        if node['id'] in ids or not re.fullmatch(r'[a-z][a-z0-9_]*', node['id']):
            raise ValueError(f'Invalid/duplicate node id: {node["id"]}')
        ids.add(node['id'])
        if node['kind'] not in KINDS or node['status'] not in STATUS:
            raise ValueError(f'Invalid node kind/status: {node["id"]}')
        a = address(node['address'])
        if node['kind'] in {'function', 'code_label'} and a & 1:
            raise ValueError('Code addresses must be even; do not store Thumb pointers as entry addresses')
        if not node['evidence']:
            raise ValueError(f'Missing identity anchors: {node["id"]}')
    for edge in data['edges']:
        if edge['source'] not in ids or edge['target'] not in ids:
            raise ValueError('Dangling edge')
        if edge['kind'] not in RELATIONS or edge['status'] not in STATUS:
            raise ValueError('Invalid edge kind/status')
        if edge['kind'] == 'direct_call':
            if address(edge['site']) & 1 or not edge.get('evidence'):
                raise ValueError('Direct calls require an even instruction site and identity evidence')
        if not edge['condition']:
            raise ValueError('Every edge needs a condition or relationship explanation')
    for owner in [*data['nodes'], *data['edges']]:
        for evidence in owner.get('evidence', []):
            a = address(evidence['address'])
            size = evidence['length']
            if not isinstance(size, int) or not 1 <= size <= 16:
                raise ValueError('Evidence must be a short identity window (1..16 bytes)')
            if not first <= a < a + size <= first + length:
                raise ValueError('Identity window is outside the profiled application segment')
            if not re.fullmatch(r'[0-9a-f]{64}', evidence['sha256']):
                raise ValueError('Invalid evidence digest')


def load() -> dict:
    data = json.loads((ROOT / 'firmware.json').read_text())
    validate(data)
    return data


def render_graph(data: dict) -> str:
    shown = [e for e in data['edges'] if e['kind'] in {'direct_call', 'indirect_call', 'function_pointer'}]
    ids = {e[k] for e in shown for k in ('source', 'target')}
    lines = ['%% Generated by map/render.py; edit firmware.json.',
             '%% Solid: direct BL. Dashed: virtual dispatch or function-pointer relationship.',
             '%% All edges are conditional; see firmware.json for the exact scope.', 'flowchart TD']
    for n in data['nodes']:
        if n['id'] in ids:
            lines.append(f'  {n["id"]}["{n["label"]}<br/>{n["address"]}"]')
    for edge in shown:
        if edge['kind'] == 'direct_call':
            lines.append(f'  {edge["source"]} -->|BL {edge["site"]}| {edge["target"]}')
        else:
            label = 'virtual call' if edge['kind'] == 'indirect_call' else 'Thumb pointer data'
            lines.append(f'  {edge["source"]} -.->|{label}| {edge["target"]}')
    return '\n'.join(lines) + '\n'


def render_index(data: dict) -> str:
    count = sum(len(x.get('evidence', [])) for x in [*data['nodes'], *data['edges']])
    lines = ['# Selected application map', '', '<!-- Generated by map/render.py; edit firmware.json. -->', '',
             f'{data["device"]}; firmware **{data["firmware"]}**.', '', data['scope'], '',
             f'{len(data["nodes"])} nodes, {len(data["edges"])} relationships, {count} hashed identity windows. '
             'No firmware payload or disassembly is embedded.', '',
             'See [call graph](calls.mmd), [format](FORMAT.md), '
             '[architecture](../docs/architecture.md), '
             '[sequencer route](../docs/sequencer.md), and '
             '[arpeggiator route](../docs/arpeggiator.md).', '',
             'All code addresses are even instruction addresses. RAM object/data addresses, flash tables, '
             'and odd Thumb pointers are different kinds. RAM entries are supported by code/literal '
             'references in the supplied image; the checker does not read device RAM.', '',
             '| Address | Kind | Provisional name | Status | Meaning |',
             '|---|---|---|---|---|']
    for n in data['nodes']:
        lines.append(f'| `{n["address"]}` | {n["kind"]} | `{n["label"]}` | {n["status"]} | {n["summary"]} |')
    lines += ['', '<details>', '<summary>Selected call graph</summary>', '', '```mermaid',
              render_graph(data).rstrip(), '```', '', '</details>', '', '## Open work', '']
    for q in data['questions']:
        lines.append(f'- **{q["question"]}** {q["next"]}')
    lines += ['', '## Reproduction', '', '```sh', 'python3 map/render.py --check',
              'python3 map/check.py --firmware "$KS37_STOCK"', '```', '',
              'The first command detects stale generated files. The second requires the exact, '
              'locally supplied firmware profile, verifies the application digest and all short '
              'windows, and decodes direct-call targets. Neither command proves execution, safety, '
              'complete control flow, or the semantic interpretation of neighboring instructions.', '']
    return '\n'.join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail on stale generated files without writing')
    args = parser.parse_args()
    data = load()
    outputs = {'index.md': render_index(data), 'calls.mmd': render_graph(data)}
    for name, content in outputs.items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                parser.exit(1, f'Stale generated file: map/{name}\n')
        else:
            path.write_text(content)
    print('Map metadata and generated files: PASS')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
